//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchOffice
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string ZIP { get; set; }
        public string Street { get; set; }
        public string ExternalNumber { get; set; }
        public string Manager { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string UrlMaps { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool IsEnabled { get; set; }
    }
}
