//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OxxoEntities : DbContext
    {
        public OxxoEntities()
            : base("name=OxxoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BranchOffice> BranchOffice { get; set; }
        public virtual DbSet<Laptop> Laptop { get; set; }
        public virtual DbSet<Toys> Toys { get; set; }
        public virtual DbSet<ExampleTable> ExampleTable { get; set; }
    }
}
